// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/epicure-upload/ResultsBlock.tsx": () => import("../components/mockups/epicure-upload/ResultsBlock.tsx"),
  "./components/mockups/epicure-upload/VisionBlock.tsx": () => import("../components/mockups/epicure-upload/VisionBlock.tsx")
};
